### PR TITLE
Contest entry for shahzaibak

### PR DESCRIPTION
**Pull request by shahzaibak**

### CODE REVIEW

**Comment by davidcuellarrdx** [comment]
Empty file

**Comment by shahzaibak** [comment]
Sorry, are you saying I’m disqualified¿? I thought it finished at 9AM ¿?


Thank you for your time,



Shahzaib Ali Khan



The City of Calgary is situated where the Bow and Elbow Rivers meet, and the Blackfoot name of this place is “Moh’kins’tsis.” The original inhabitants of Southern Alberta include the Siksika, Piikani, Kainai, Tsuut’ina, Chiniki, Bearspaw, Wesley, and Métis First Nations.

________________________________

**Comment by shahzaibak** [comment]
it’s currently 7AM for me sorry I forgot to convert time zones


Thank you for your time,



Shahzaib Ali Khan



The City of Calgary is situated where the Bow and Elbow Rivers meet, and the Blackfoot name of this place is “Moh’kins’tsis.” The original inhabitants of Southern Alberta include the Siksika, Piikani, Kainai, Tsuut’ina, Chiniki, Bearspaw, Wesley, and Métis First Nations.

________________________________

**Comment by shahzaibak** [comment]
Super_dapp

**Comment by shahzaibak** [comment]
that didnt work

**Pull request closed without merging**
