### PR TITLE
My submition

### PR DESCRIPTION
**Pull request by gald33**
Comments are on the readme.MD inside the folder.
One more general comment I'd like to make is that I didn't clear a bucket with take_all() but the calculations should have it exactly cleared on the last pass. In my eyes that's the safer way to go because I do want everything to fail had I made a mistake in the calculation. The rest you can see in the readme :)

### CODE REVIEW

**Comment by cbisaillon** [comment]
Hi, the deadline was the 18th of March at 12:00 UTC. 
I will write feedback on your code, but you will not be eligible for prizes. Sorry about that.

**Comment by gald33** [comment]
oh, I thought 12 at night.
oh no.
Would I get the NFT at least?
בברכה
גל דנינו

**Comment by gald33** [comment]
I also assumed the Hawaii time convention...

**Comment by cbisaillon** [comment]
I am sorry but we cannot change the rules. You will still get feedback on your code

**Comment by gald33** [comment]
> I am sorry but we cannot change the rules. You will still get feedback on your code

I'm glad about getting a feedback, thanks, but disappointed about not getting the NFT, I thought I was submitting on time.

**Pull request merged**
